apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "lbsubnet"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: my-nginx