apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    aadpodidbinding: app
spec:
  containers:
  - name: toolbox
    image: docker.io/bithacker/toolbox:latest
    # command: [ "/bin/bash", "-c", "--" ]
    # args: [ "while true; do sleep 30; done;" ]
    command: [ "tail" ]
    args: [ "-f", "/dev/null" ]